name: Wirtschaftswunder
favicon: null
layout_spectrum: 0.6650235850829631
typography_spectrum: 0.8348161007743329
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6383832008577883
  lightness: 0.38628332456573844
  saturation: 0.6038228853140026
  rhythmicContrast: 0.7251994090620428
purpose: []
